// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myohtqgqyslonvvakwmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15b2h0cWdxeXNsb252dmFrd21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTM4OTgsImV4cCI6MjA3MTM2OTg5OH0.CdsLzKumHftaFPhNoJwQt4IePCLTfxVbbogY7WTZSuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});